# // Inserir eleitor
# # CREATE TABLE eleitor(
# # cpf varchar(11) NOT NULL,
# # nome varchar(100) NOT NULL,
# # data_nascimento varchar(10) NOT NULL,
# # nome_mae varchar(100) NOT NULL,
# # cep varchar(8) NOT NULL,
# # nro_endereco varchar(10) NOT NULL,
# # nro_titulo varchar(14) NOT NULL,
# # situacao varchar(20) NOT NULL,
# # secao varchar(4) NOT NULL,
# # zona varchar(4) NOT NULL,
# # local_votacao varchar(200) NOT NULL,
# # endereco_votacao varchar(200) NOT NULL,
# # bairro varchar(100) NOT NULL,
# # municipio_uf varchar(100) NOT NULL,
# # pais varchar(50) NOT NULL,
# # PRIMARY KEY (cpf)
# # );
# POST http://127.0.0.1:5000/eleitor
# Content-Type: application/json
# // OBS: É necessário pular uma linha, quando existir um corpo (body) 

# {
#   "cpf": 12345678900,
#   "nome": "Fulano",
#   "data_nascimento": "1/01/2001",
#   "nome_mae": "Mae do Fulano",
#   "cep": "12345",
#   "nro_endereco": "01",
#   "nro_titulo": "12345678900000",
#   "situacao": "Regular",
#   "secao": "1234",
#   "zona": "123",
#   "local_votacao": "Escolar",
#   "endereco_votacao": "Leste",
#   "bairro": "Manoa",
#   "municipio_uf": "Manaus",
#   "pais": "Brasil"
# }
# // Utiliza-se obrigatoriamente no início da linha os simbolos: ###
# // para separar uma requisção da outra. 
# ###

# POST http://127.0.0.1:5000/eleitor
# Content-Type: application/json
# // OBS: É necessário pular uma linha, quando existir um corpo (body) 

# {
#   "cpf": 12345678910,
#   "nome": "Beltrano",
#   "data_nascimento": "1/01/2002",
#   "nome_mae": "Mae do Beltrano",
#   "cep": "54321",
#   "nro_endereco": "02",
#   "nro_titulo": "12345678900001",
#   "situacao": "Irregular",
#   "secao": "4321",
#   "zona": "321",
#   "local_votacao": "Estadual",
#   "endereco_votacao": "Norte",
#   "bairro": "Colonia",
#   "municipio_uf": "Manaus",
#   "pais": "Brasil"
# }
# // Utiliza-se obrigatoriamente no início da linha os simbolos: ###
# // para separar uma requisção da outra. 
# ###

# // Listar todos os usuários em ordem alfabética do name
# GET http://127.0.0.1:5000/eleitor
# Content-Type: application/json
# ###

# // Obter usuário pelo cpf
# //GET http://127.0.0.1:5000/eleitor/{cpf}
# GET http://127.0.0.1:5000/eleitor/12345678900
# Content-Type: application/json
# ###

# // Alterar usuário pelo cpf
# // OBS: obrigado preencher o campo cpf
# PUT http://127.0.0.1:5000/eleitor
# Content-Type: application/json
# // OBS: É necessário pular uma linha, quando existir um corpo (body) 

# {
#   "cpf": 12345678900,
#   "nome": "Beltrano",
#   "data_nascimento": "1/01/2002",
#   "nome_mae": "Mae do Beltrano",
#   "cep": "54321",
#   "nro_endereco": "02",
#   "nro_titulo": "12345678900001",
#   "situacao": "Irregular",
#   "secao": "4321",
#   "zona": "321",
#   "local_votacao": "Estadual",
#   "endereco_votacao": "Norte",
#   "bairro": "Colonia",
#   "municipio_uf": "Manaus",
#   "pais": "Brasil"
# }
# ###

# // Obter usuário pelo cpf
# GET http://127.0.0.1:5000/eleitor/70390243221
# Content-Type: application/json
# ###

# // Deletar usuário pelo cpf
# DELETE http://127.0.0.1:5000/eleitor/4981577257
# Content-Type: application/json

# // Utiliza-se obrigatoriamente no início da linha os simbolos: ###
# // para separar uma requisção da outra. 




POST http://127.0.0.1:5000/usuario
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
    "nome": "Lucas da Rocha Andrade",
    "login": "Lucas",
    "senha": "1234",
    "email": "lrandrade20@gmail.com"
}
###

POST http://127.0.0.1:5000/usuario
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
    "nome": "Bruno Pereira",
    "login": "Bruno",
    "senha": "1234",
    "email": "bruno.pereira@ifam.edu.br"
}
###

POST http://127.0.0.1:5000/usuario
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
    "nome": "Caio Cesar",
    "login": "Caio",
    "senha": "1234",
    "email": "7caioc@gmail.com"
}

###
// Listar todos os usuários em ordem alfabética do nome
GET http://127.0.0.1:5000/usuario 
Content-Type: application/json

###
// Obter usuário pelo ID
//GET http://127.0.0.1:5000/usuario/id
GET http://127.0.0.1:5000/usuario/6
Content-Type: application/json

###
// Deletar usuário pelo ID
// http://127.0.0.1:5000/usuario/id
DELETE http://127.0.0.1:5000/usuario/2
Content-Type: application/json

###
POST http://127.0.0.1:5000/eleitor
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
  "cpf": 12345678900,
  "nome": "Fulano",
  "data_nascimento": "1/01/2001",
  "nome_mae": "Mae do Fulano",
  "cep": "12345",
  "nro_endereco": "01",
  "nro_titulo": "12345678900000",
  "situacao": "Regular",
  "secao": "1234",
  "zona": "123",
  "local_votacao": "Escolar",
  "endereco_votacao": "Leste",
  "bairro": "Manoa",
  "municipio_uf": "Manaus",
  "pais": "Brasil"
}
// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###

POST http://127.0.0.1:5000/eleitor
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
  "cpf": 12345678910,
  "nome": "Beltrano",
  "data_nascimento": "1/01/2002",
  "nome_mae": "Mae do Beltrano",
  "cep": "54321",
  "nro_endereco": "02",
  "nro_titulo": "12345678900001",
  "situacao": "Irregular",
  "secao": "4321",
  "zona": "321",
  "local_votacao": "Estadual",
  "endereco_votacao": "Norte",
  "bairro": "Colonia",
  "municipio_uf": "Manaus",
  "pais": "Brasil"
}
// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###

// Listar todos os usuários em ordem alfabética do name
GET http://127.0.0.1:5000/eleitor
Content-Type: application/json

###
// Deletar usuário pelo cpf
DELETE http://127.0.0.1:5000/eleitor/4981577257
Content-Type: application/json

###
// Obter usuário pelo cpf
//GET http://127.0.0.1:5000/eleitor/{cpf}
GET http://127.0.0.1:5000/eleitor/12345678900
Content-Type: application/json
###

// Alterar usuário pelo cpf
// OBS: obrigado preencher o campo cpf
PUT http://127.0.0.1:5000/eleitor
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
  "cpf": 12345678900,
  "nome": "Beltrano",
  "data_nascimento": "1/01/2002",
  "nome_mae": "Mae do Beltrano",
  "cep": "54321",
  "nro_endereco": "02",
  "nro_titulo": "12345678900001",
  "situacao": "Irregular",
  "secao": "4321",
  "zona": "321",
  "local_votacao": "Estadual",
  "endereco_votacao": "Norte",
  "bairro": "Colonia",
  "municipio_uf": "Manaus",
  "pais": "Brasil"
}
###

// Obter usuário pelo cpf
GET http://127.0.0.1:5000/eleitor/70390243221
Content-Type: application/json


// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra.